/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simplewebbrowserexample;

import chrriis.common.UIUtils;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author shuai
 */
public class MapPanel extends javax.swing.JPanel {

    private JWebBrowser webBrowser;

    /**
     * Creates new form MapPanel
     */
    public MapPanel() {
        initComponents();
        webBrowser = new JWebBrowser();
        webBrowser.setJavascriptEnabled(true);
        webBrowser.setBarsVisible(false);
        URL url = Toolkit.class.getResource("/resource/newhtml1.html");
        webBrowser.navigate(url.toString());

//        setLayout(new BorderLayout());
        add(webBrowser, BorderLayout.CENTER);
    }
    
    public void addMarker(double lng, double lat){
        String func = webBrowser.createJavascriptFunctionCall("addMarker", lng, lat);
        webBrowser.executeJavascript(func);
    }
    
    public static void main(String[] args) {
        NativeInterface.open();
        UIUtils.setPreferredLookAndFeel();
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add(new MapPanel(), BorderLayout.CENTER);
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setLocationByPlatform(true);
//                frame.setSize(1280, 800);
                frame.setVisible(true);
            }
        });
        NativeInterface.runEventPump();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addMarker(39.9, 116.4);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
